### ISSUE TITLE
Not deploy docker-compose

### ISSUE THREAD

**Issue by Kaiden0001** [omkarcloud/botasaurus-starter#1]
### HI
 
 ```bash
sudo docker compose up --build
```
```bash
 => [bot-1 6/7] COPY . /app                                                                                                                                                                                        2.0s
 => ERROR [bot-1 7/7] RUN python run.py install                                                                                                                                                                    2.7s
------
 > [bot-1 7/7] RUN python run.py install:
1.449 Traceback (most recent call last):
1.449   File "/app/run.py", line 1, in <module>
1.449     import backend.scrapers
1.449   File "/app/backend/scrapers.py", line 2, in <module>
1.449     from src.scrape_heading_task import scrape_heading_task
1.449   File "/app/src/scrape_heading_task.py", line 1, in <module>
1.449     from botasaurus.request import request, Request
1.449   File "/usr/local/lib/python3.9/site-packages/botasaurus/request.py", line 1, in <module>
1.449     from .request_decorator import request
1.449   File "/usr/local/lib/python3.9/site-packages/botasaurus/request_decorator.py", line 5, in <module>
1.449     from .create_request import create_request
1.449   File "/usr/local/lib/python3.9/site-packages/botasaurus/create_request.py", line 1, in <module>
1.450     from botasaurus_requests import Request
1.450   File "/usr/local/lib/python3.9/site-packages/botasaurus_requests/__init__.py", line 26, in <module>
1.450     from .response import Response, ProcessResponse
1.450   File "/usr/local/lib/python3.9/site-packages/botasaurus_requests/response.py", line 7, in <module>
1.450     import cchardet as chardet
1.450 ModuleNotFoundError: No module named 'cchardet'
------
failed to solve: process "/bin/sh -c python run.py install" did not complete successfully: exit code: 1
```
I updated requirements.txt
```
botasaurus
botasaurus_server
+cchardet
```
 ```bash
sudo docker compose up --build
```
```
 => ERROR [bot-1 7/7] RUN python run.py install                                                                                                                                                                   23.4s
------
 > [bot-1 7/7] RUN python run.py install:
1.572 Downloading cgo library ...
20.89 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 786.1 kB/s
20.91 Downloading Chrome version history...
21.20 Downloading Firefox version history...
21.62 Traceback (most recent call last):
21.62   File "/app/run.py", line 1, in <module>
21.62     import backend.scrapers
21.62   File "/app/backend/scrapers.py", line 2, in <module>
21.62     from src.scrape_heading_task import scrape_heading_task
21.62   File "/app/src/scrape_heading_task.py", line 1, in <module>
21.62     from botasaurus.request import request, Request
21.62   File "/usr/local/lib/python3.9/site-packages/botasaurus/request.py", line 1, in <module>
21.62     from .request_decorator import request
21.62   File "/usr/local/lib/python3.9/site-packages/botasaurus/request_decorator.py", line 5, in <module>
21.62     from .create_request import create_request
21.62   File "/usr/local/lib/python3.9/site-packages/botasaurus/create_request.py", line 1, in <module>
21.62     from botasaurus_requests import Request
21.62   File "/usr/local/lib/python3.9/site-packages/botasaurus_requests/__init__.py", line 31, in <module>
21.62     from .request_class import Request
21.62   File "/usr/local/lib/python3.9/site-packages/botasaurus_requests/request_class.py", line 7, in <module>
21.62     class Request(Session):
21.62   File "/usr/local/lib/python3.9/site-packages/botasaurus_requests/request_class.py", line 14, in Request
21.62     url: str | bytes,
21.62 TypeError: unsupported operand type(s) for |: 'type' and 'type'
------
failed to solve: process "/bin/sh -c python run.py install" did not complete successfully: exit code: 1
```
### What's wrong?

**Comment by Kaiden0001** [comment]
https://github.com/omkarcloud/botasaurus-starter/pull/4
