### ISSUE TITLE
NODE_TYPE=MASTER  (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by Kaiden0001** [omkarcloud/botasaurus-starter#2]
docker-compose
```bash
version: "3.8"
services:
  bot-1:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - KUBERNETES_SERVICE_HOST=True
      - NODE_TYPE=MASTER
    restart: always
    ports:
      - "3000:3000"
      - "8000:8000"
```
## Traceback
```bash
(.venv) ~/PythonProjects/TestNewBotasaurus/botasaurus-starter git:[master]
python3 run.py
Traceback (most recent call last):
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/botasaurus-starter/run.py", line 2, in <module>
    from botasaurus_server.run import run
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/run.py", line 8, in <module>
    from .app import run_backend
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/app.py", line 7, in <module>
    from . import master_routes
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/master_routes.py", line 1, in <module>
    from .task_routes import OK_MESSAGE # imports all routes as well
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/task_routes.py", line 14, in <module>
    from .executor import executor
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/executor.py", line 4, in <module>
    from .master_executor import MasterExecutor
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/master_executor.py", line 2, in <module>
    from .task_executor import TaskExecutor
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/task_executor.py", line 8, in <module>
    from .db_setup import Session
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/db_setup.py", line 25, in <module>
    create_database()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/botasaurus_server/db_setup.py", line 23, in create_database
    Base.metadata.create_all(engine)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5857, in create_all
    bind._run_ddl_visitor(
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3250, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3240, in begin
    with self.connect() as conn:
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
    return self._connection_cls(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/kaiden/PythonProjects/TestNewBotasaurus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by Kaiden0001** [comment]
I don't need this
